Fix looping over string in findBy function
Strings are not cleaned up in mapComponent function for shallow rendering and strings have method length which was causing it to crash with following error message

Failures:
1) createComponent.shallow should find findByComponent component rendering its children
1.1) TypeError: c.findBy is not a function
    TypeError: c.findBy is not a function
        at /Users/kamil/Workspace/react-unit/dist/react-unit.js:66:18
        at _map (/Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:376:27)
        at /Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:3919:23
        at /Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:178:28
        at f1 (/Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:156:27)
        at /Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:384:35
        at /Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:384:35
        at /Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:384:35
        at f1 (/Users/kamil/Workspace/react-unit/node_modules/ramda/dist/ramda.js:156:27)
        at Component.findBy (/Users/kamil/Workspace/react-unit/dist/react-unit.js:67:10)